name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # ou a versão que você estiver usando

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Lint
        run: npm run lint

      - name: Rodar Build
        run: npm run build

      - name: Rodar Testes
        run: npm run test
